-- CREATE SCHEMA `student_db`;
/* CREATE TABLE `student`
(`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`name` VARCHAR(255) NOT NULL, 
`email` VARCHAR(255) NOT NULL, 
`phone` INT NOT NULL, 
`class_id` INT NOT NULL,
PRIMARY KEY(`id`),
UNIQUE INDEX `name_UNIQUE`(`name` ASC)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
*/


CREATE TABLE `class` (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`name` VARCHAR(255) NOT NULL, 
`begins` DATETIME NOT NULL, 
`ends` DATETIME NOT NULL,
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
